# @package _global_

env:
  config:
    ### Respawn related params
    mimic_motion_sampling:
      init_start_prob: 0.15
      init_random_prob: 0.05

    mimic_dynamic_sampling:
      enabled: True
      dynamic_weight_max: null
      sampling_criteria: mimic_early_termination
      bucket_width: 2.0

# At evaluation, disable dynamic sampling
eval_overrides:
  env:
    config:
      mimic_dynamic_sampling:
        enabled: False