# @package _global_

defaults:
  - humanoid

# Env structure
env:
  _target_: phys_anim.envs.amp.${backbone}.DiscHumanoid
  config:
    # Simulation params
    ## Observations
    discriminator_obs_historical_steps: 10
    disable_discriminator: False
    discriminator_obs_size_per_step: ${eval:13+${robot.dof_obs_size}+${robot.number_of_actions}+3*${robot.num_key_bodies}}

    ## Motion-related params
    ### Respawn related params
    state_init: Random

# Globally accessible parameters
