# @package _global_

env:
  config:
    masked_mimic_masking:
      joint_masking:
        masked_mimic_fixed_conditioning:
          - body_name: Pelvis
            constraint_state: 0


        masked_mimic_time_gap_probability: 0
        masked_mimic_repeat_mask_probability: 1