# @package _global_

defaults:
  - /algo: infomax
  - /env: amp

env:
  config:
    state_init: Random
    # Currently hybrid respawn is not supported
#    state_init: Hybrid
#    hybrid_init_prob: 0.5

experiment_name: ase