# @package _global_

defaults:
  - /algo: mimic_vae_dagger
  - /env: masked_mimic
  - /opt/disable_discriminator  # Default mimic experiments don't use the discriminator
  - /terrain/terrain_obs
  - /terrain: complex
  - /scenes/samp
  - /opt/masked_mimic/transformer
  - /opt/masked_mimic/text_conditioning
  - /opt/masked_mimic/historical_pose_obs
  - /opt/masked_mimic/samp_scenes
  - /opt/mimic/global_tracking
  - /opt/mimic/early_termination_tracking_err
  - /opt/mimic/dynamic_sampling

experiment_name: masked_mimic

# MaskedMimic has unused parameters.
# We need to investigate why this is the case.
# For now this flag helps avoid issues in multi-gpu/multi-node training.
fabric:
  strategy:
    find_unused_parameters: true
