# @package _global_
defaults:
  - /env/inversion/base

env:
  _target_: phys_anim.envs.masked_mimic_inversion.reach.${backbone}.MaskedMimicReachHumanoid
  config:
    task_obs_size: ${env.config.reach_params.obs_size}
    text_command: a person reaches with its right hand
    reach_params:
      reach_body_name: R_Hand
      change_steps_min: 90
      change_steps_max: 120
      tar_dist_max: 1.0
      tar_height_min: 0.05
      tar_height_max: 1.6
      reach_steps_min: 60
      reach_steps_max: 61
      obs_size: 3