# @package _global_
defaults:
  - /env/inversion/base

env:
  _target_: phys_anim.envs.masked_mimic_inversion.steering.${backbone}.MaskedMimicDirectionHumanoid
  config:
    task_obs_size: ${env.config.steering_params.obs_size}
    steering_params:
      heading_change_steps_min: 40
      heading_change_steps_max: 150
      random_heading_probability: 0.2
      standard_heading_change: 1.57
      tar_speed_min: 1.2
      tar_speed_max: 6
      change_steps_min: 199
      change_steps_max: 200
      standard_speed_change: 0.3
      stop_probability: 0.05
      enable_rand_heading: True
      obs_size: 3
      log_speed: False
      use_current_pose_obs: False
