# @package _global_

# Robot
backbone: isaacsim

robot:
  asset:
    asset_file_name: "usd/${robot.asset.robot_type}.usda"

# Environment config
env:
  config:
    simulator:
      headless: ${headless}
      test: False

      sim:
        use_gpu_pipeline: True
        gravity: [0.0, 0.0, -9.81]
        enable_scene_query_support: False
        use_fabric: True
        disable_contact_processing: True

        light_type: distant # Supported: 'sphere', 'distant'

        # set to True if you use camera sensors in the environment
        enable_cameras: False

        default_physics_material: ${..plane}

        physx:
          worker_thread_count: ${.num_threads}
          use_gpu: True
          solver_position_iteration_count: ${.num_position_iterations}
          solver_velocity_iteration_count: ${.num_velocity_iterations}
          friction_offset_threshold: 0.04
          friction_correlation_distance: 0.025
          enable_sleeping: True
          enable_stabilization: True

          # GPU buffers
          gpu_max_rigid_contact_count: 524288
          gpu_max_rigid_patch_count: 81920
          gpu_found_lost_pairs_capacity: 8192
          gpu_found_lost_aggregate_pairs_capacity: 262144
          gpu_total_aggregate_pairs_capacity: 8192
          gpu_max_soft_body_contacts: 1048576
          gpu_max_particle_contacts: 1048576
          gpu_heap_capacity: 67108864
          gpu_temp_buffer_capacity: 16777216
          gpu_max_num_partitions: 8

        Humanoid:
          # -1 to use default values
          override_usd_defaults: False
          enable_self_collisions: True
          enable_gyroscopic_forces: True
          # also in stage params
          # per-actor
          solver_position_iteration_count: 4
          solver_velocity_iteration_count: 0
          sleep_threshold: 0.005
          stabilization_threshold: 0.001
          # per-body
          density: -1
          max_depenetration_velocity: 10.0

    cameras:
      - name: birds_eye_view
        position:
          - 10.0
          - 10.0
          - 100.0
        frequency: 15
        resolution:
          - 256
          - 256
        orientation: # degrees
          - 270.0
          - 90.0
          - 0.0
