# @package _global_

defaults:
  - mimic_vae

algo:
  _target_: phys_anim.agents.mimic_vae_dagger.MimicVAEDagger
  config:
    # Dagger parameters
    dagger:
      bc_coeff: 1.
      gt_actor_path: ${gt_actor_path}
      only_bc: True
      collect_data_with_expert: False

gt_actor_path: null

eval_overrides:
  gt_actor_path: null
  algo:
    config:
      dagger:
        collect_data_with_expert: False