# @package _global_

algo:
  config:
    models:
      mimic_target_pose_model:
        _target_: phys_anim.agents.models.common.Flatten
        config:
          normalize_obs: ${algo.config.normalize_obs}
          obs_clamp_value: ${algo.config.obs_clamp_value}
        num_in: ${eval:${env.config.mimic_target_pose.num_future_steps}*${env.config.mimic_target_pose.num_obs_per_target_pose}}
        num_out: ${.num_in}

    actor:
      config:
        mu_model:
          config:
            units: [1024, 1024, 1024]
            extra_inputs:
              mimic_target_poses: ${algo.config.models.mimic_target_pose_model}

    critic:
      config:
        units: [1024, 1024, 1024]
        extra_inputs:
          mimic_target_poses: ${algo.config.models.mimic_target_pose_model}

    extra_inputs:
      mimic_target_poses:
        retrieve_from_env: True
        dtype: float
        size: ${algo.config.models.mimic_target_pose_model.num_in}

env:
  config:
    max_episode_length: 300

    mimic_target_pose:
      enabled: True
      type: max-coords-future-rel
      num_future_steps: 5
