# @package _global_

defaults:
  - base

robot:
  bfs_body_names: ['Pelvis', 'L_Hip', 'R_Hip', 'Torso', 'L_Knee', 'R_Knee', 'Spine', 'L_Ankle', 'R_Ankle', 'Chest', 'L_Toe', 'R_Toe', 'Neck', 'L_Thorax', 'R_Thorax', 'Head', 'L_Shoulder', 'R_Shoulder', 'L_Elbow', 'R_Elbow', 'L_Wrist', 'R_Wrist', 'L_Hand', 'R_Hand']
  dfs_body_names: ['Pelvis', 'L_Hip', 'L_Knee', 'L_Ankle', 'L_Toe', 'R_Hip', 'R_Knee', 'R_Ankle', 'R_Toe', 'Torso', 'Spine', 'Chest', 'Neck', 'Head', 'L_Thorax', 'L_Shoulder', 'L_Elbow', 'L_Wrist', 'L_Hand', 'R_Thorax', 'R_Shoulder', 'R_Elbow', 'R_Wrist', 'R_Hand']

  bfs_dof_names: ['L_Hip_x', 'L_Hip_y', 'L_Hip_z', 'R_Hip_x', 'R_Hip_y', 'R_Hip_z', 'Torso_x', 'Torso_y', 'Torso_z', 'L_Knee_x', 'L_Knee_y', 'L_Knee_z', 'R_Knee_x', 'R_Knee_y', 'R_Knee_z', 'Spine_x', 'Spine_y', 'Spine_z', 'L_Ankle_x', 'L_Ankle_y', 'L_Ankle_z', 'R_Ankle_x', 'R_Ankle_y', 'R_Ankle_z', 'Chest_x', 'Chest_y', 'Chest_z', 'L_Toe_x', 'L_Toe_y', 'L_Toe_z', 'R_Toe_x', 'R_Toe_y', 'R_Toe_z', 'Neck_x', 'Neck_y', 'Neck_z', 'L_Thorax_x', 'L_Thorax_y', 'L_Thorax_z', 'R_Thorax_x', 'R_Thorax_y', 'R_Thorax_z', 'Head_x', 'Head_y', 'Head_z', 'L_Shoulder_x', 'L_Shoulder_y', 'L_Shoulder_z', 'R_Shoulder_x', 'R_Shoulder_y', 'R_Shoulder_z', 'L_Elbow_x', 'L_Elbow_y', 'L_Elbow_z', 'R_Elbow_x', 'R_Elbow_y', 'R_Elbow_z', 'L_Wrist_x', 'L_Wrist_y', 'L_Wrist_z', 'R_Wrist_x', 'R_Wrist_y', 'R_Wrist_z', 'L_Hand_x', 'L_Hand_y', 'L_Hand_z', 'R_Hand_x', 'R_Hand_y', 'R_Hand_z']
  dfs_dof_names: ['L_Hip_x', 'L_Hip_y', 'L_Hip_z', 'L_Knee_x', 'L_Knee_y', 'L_Knee_z', 'L_Ankle_x', 'L_Ankle_y', 'L_Ankle_z', 'L_Toe_x', 'L_Toe_y', 'L_Toe_z', 'R_Hip_x', 'R_Hip_y', 'R_Hip_z', 'R_Knee_x', 'R_Knee_y', 'R_Knee_z', 'R_Ankle_x', 'R_Ankle_y', 'R_Ankle_z', 'R_Toe_x', 'R_Toe_y', 'R_Toe_z', 'Torso_x', 'Torso_y', 'Torso_z', 'Spine_x', 'Spine_y', 'Spine_z', 'Chest_x', 'Chest_y', 'Chest_z', 'Neck_x', 'Neck_y', 'Neck_z', 'Head_x', 'Head_y', 'Head_z', 'L_Thorax_x', 'L_Thorax_y', 'L_Thorax_z', 'L_Shoulder_x', 'L_Shoulder_y', 'L_Shoulder_z', 'L_Elbow_x', 'L_Elbow_y', 'L_Elbow_z', 'L_Wrist_x', 'L_Wrist_y', 'L_Wrist_z', 'L_Hand_x', 'L_Hand_y', 'L_Hand_z', 'R_Thorax_x', 'R_Thorax_y', 'R_Thorax_z', 'R_Shoulder_x', 'R_Shoulder_y', 'R_Shoulder_z', 'R_Elbow_x', 'R_Elbow_y', 'R_Elbow_z', 'R_Wrist_x', 'R_Wrist_y', 'R_Wrist_z', 'R_Hand_x', 'R_Hand_y', 'R_Hand_z']

  # Observation parameters
  dof_obs_size: 138
  number_of_actions: 69
  self_obs_max_coords_size: 358  # ${eval:1+24*(3+6+3+3)-3}

  # Control parameters
  dfs_dof_body_ids: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]

  key_bodies: [ "R_Ankle", "L_Ankle", "L_Hand", "R_Hand" ]
  non_termination_contact_bodies: [ "R_Ankle", "L_Ankle", "R_Toe", "L_Toe" ]
  right_foot_name: "R_Ankle"
  left_foot_name: "L_Ankle"

  asset:
    robot_type: smpl_humanoid
    filter_ints: [ 0, 0, 7, 16, 12, 0, 56, 2, 33, 128, 0, 192, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ]
