# @package _global_

# Some default parameters for when using the legged robot, such as H1.
# These robots use torque control and have a different set of rewards.
env:
  config:
    mimic_reward_config:
      component_weights:
        pow_rew_w: 0

algo:
  config:
    bounds_loss_coef: 0.0
