# @package _global_

algo:
  config:
    eval_callbacks:
      export_motion_cb:
        _target_: phys_anim.agents.callbacks.export_motion.ExportMotion
        config:
          record_dir: output/recordings
          store_poselib: False
          index_offset: ${env.config.motion_index_offset}

env:
  config:
    export_motion: True
