# @package _global_

algo:
  config:
    actor:
      config:
        sigma_schedule:
          #  mimic_success: True
          init_logstd: ${..init_logstd}
          end_logstd: -6
          start_epoch: 8000
          end_epoch: 60000
